/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PoWRegistry {
  export type SnapshotStruct = {
    artifactHash: BytesLike;
    skillScores: BigNumberish[];
    githubIdentity: AddressLike;
    timestamp: BigNumberish;
    exists: boolean;
  };

  export type SnapshotStructOutput = [
    artifactHash: string,
    skillScores: bigint[],
    githubIdentity: string,
    timestamp: bigint,
    exists: boolean
  ] & {
    artifactHash: string;
    skillScores: bigint[];
    githubIdentity: string;
    timestamp: bigint;
    exists: boolean;
  };
}

export interface PoWRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorSnapshot"
      | "getSkillScores"
      | "getSnapshot"
      | "snapshots"
      | "verifiedHashes"
      | "verifySnapshot"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SnapshotAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorSnapshot",
    values: [BytesLike, BigNumberish[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSkillScores",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSnapshot",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "snapshots",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySnapshot",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSkillScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "snapshots", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifiedHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySnapshot",
    data: BytesLike
  ): Result;
}

export namespace SnapshotAnchoredEvent {
  export type InputTuple = [
    user: AddressLike,
    artifactHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    artifactHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    artifactHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PoWRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PoWRegistry;
  waitForDeployment(): Promise<this>;

  interface: PoWRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorSnapshot: TypedContractMethod<
    [
      artifactHash: BytesLike,
      skillScores: BigNumberish[],
      githubIdentity: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getSkillScores: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getSnapshot: TypedContractMethod<
    [user: AddressLike],
    [PoWRegistry.SnapshotStructOutput],
    "view"
  >;

  snapshots: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        artifactHash: string;
        githubIdentity: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  verifiedHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifySnapshot: TypedContractMethod<[hash: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorSnapshot"
  ): TypedContractMethod<
    [
      artifactHash: BytesLike,
      skillScores: BigNumberish[],
      githubIdentity: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSkillScores"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSnapshot"
  ): TypedContractMethod<
    [user: AddressLike],
    [PoWRegistry.SnapshotStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "snapshots"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        artifactHash: string;
        githubIdentity: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifiedHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifySnapshot"
  ): TypedContractMethod<[hash: BytesLike], [boolean], "view">;

  getEvent(
    key: "SnapshotAnchored"
  ): TypedContractEvent<
    SnapshotAnchoredEvent.InputTuple,
    SnapshotAnchoredEvent.OutputTuple,
    SnapshotAnchoredEvent.OutputObject
  >;

  filters: {
    "SnapshotAnchored(address,bytes32,uint256)": TypedContractEvent<
      SnapshotAnchoredEvent.InputTuple,
      SnapshotAnchoredEvent.OutputTuple,
      SnapshotAnchoredEvent.OutputObject
    >;
    SnapshotAnchored: TypedContractEvent<
      SnapshotAnchoredEvent.InputTuple,
      SnapshotAnchoredEvent.OutputTuple,
      SnapshotAnchoredEvent.OutputObject
    >;
  };
}
